# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# RUN_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set RUN_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The COMPILE_RESULT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/gsl/build-mic/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/gsl/build-mic/CMakeFiles/cmTC_b5b04-RUN_RESULT
# Run arguments : 
#    Called from: [2]	/home/gsl/CMakeLists.txt
#                 [1]	/home/gsl/CMakeLists.txt

set( RUN_RESULT 
     "0"
     CACHE STRING "" FORCE)

